stages:
- export
- deploy

Export:
    only:
    - master
    stage: export
    script:
    - export

oracle-ssh:
    only:
    - master
    stage: deploy
    script: 
    - echo "$KEY" | ssh-add - > /dev/null
    - ssh -o StrictHostKeyChecking=no "$USER"@"$SERVER" -p "$PORT" "cd /var/www && git reset --hard && git pull && cp -f lesson2/public-html/* www/"
